language: node_js
node_js:
  - 7

before_install:
  - echo "deb [trusted=yes] https://apt.secrethub.io stable main" | sudo tee /etc/apt/sources.list.d/secrethub.sources.list
  - sudo apt-get update
  - sudo apt-get install -y secrethub-cli

script:
  - secrethub run -- node test.js
